### ISSUE TITLE
Inconsistency with "enumerable"

### ISSUE THREAD

**Issue by mlutze** [SSoelvsten/cs-dict#18]
![image](https://github.com/SSoelvsten/cs-dict/assets/19153692/2828f77c-535a-47b9-b512-0674a759af61)

The translation for "recursively enumerable" doesn't match that for "enumerable". Is this intentional?

**Comment by SSoelvsten** [comment]
Good point. Thanks for pointing it out! I skimmed through DDO, found the Norwegian "Recursively Enumerabel" and some high-school material on set theory that provides a translation.
