### ISSUE TITLE
Request: "throw an exception"

### ISSUE THREAD

**Issue by mlutze** [SSoelvsten/cs-dict#19]
Do you take requests?

I have not been able to find a translation for "throwing an exception" à la Java. I'm using "at kaste et fejl" for the moment, but I'm not convinced that's quite right, especially since Java distinguishes between exceptions (recoverable) and errors (unrecoverable).

**Comment by SSoelvsten** [comment]
Of course! I should fix the README such that this is much clearer that requests are very welcome. :slightly_smiling_face: 

- [ ] "throw" -> "kaste"
- [ ] "error" -> "fejl"
- [ ] "exception" -> ???

**Comment by SSoelvsten** [comment]
Bærbak did on-the-fly the same kind of reasoning, so I feel that confirms it is a reasonable translation.
