### ISSUE TITLE
Feature request: gender and inflections 

### ISSUE THREAD

**Issue by mlutze** [SSoelvsten/cs-dict#7]
It would be nice for Danish learners if the dictionary included additional information about how to use the word grammatically. Alternatively, making each entry link to e.g. the corresponding DDO entry would save a couple of seconds for the user.

**Comment by SSoelvsten** [comment]
Very good point - sorry I did not think of that use-case! I'm going to take a stab at it on Saturday. :slightly_smiling_face:

**Comment by SSoelvsten** [comment]
It will of course take me some time to go over every word. But just to be sure, this is what you are requesting?
![billede](https://github.com/SSoelvsten/cs-dict/assets/14313096/0ae783d1-2efe-49ac-9aa2-52dd1f16438d)

**Comment by mlutze** [comment]
Looks great, thanks!
